### ISSUE TITLE
Spell uses not working

### ISSUE THREAD

**Issue by TheAlaine** [Xacus/demonlord#11]
Hi,

I configured the uses for spells but when i use them they do not get lower/used up like talents do.
It seemed to work sometimes while i tested stuff as GM but it was pretty random and i could not do it on purpose. ( could have been mislicks as far as i know ).

Regards,

TheAlaine

**Comment by Xacus** [comment]
No, I didn't make that part yet or maybe partly. I'll fix that.

**Comment by TheAlaine** [comment]
> No, I didn't make that part yet or maybe partly. I'll fix that.

Is it possible to not make it roll/activate if it is out of uses?
Because if a talent is 0/1 and you click it it activates in the chat window and resets the talent to 1/1.

If spells work like that too it would make the skill bar a little less good for spells because you still have to look in the sheet to see if you have casts for this spell left.

**Comment by TheAlaine** [comment]
Fixed in 1.1.4,
Thank you :)
