### ISSUE TITLE
Problems with spells in 1.1.4

### ISSUE THREAD

**Issue by TheAlaine** [Xacus/demonlord#13]
Ok new Problems with 1.1.4:

1.
If you attack a character with an Spell that includes an VS roll the field for the defense side is empty ( it should display the actual value here). This includes spells from creatures and characters. For spell attacks on creatures it shows the "?" like intended.

2.
If you have an Spell with an challenge roll the button in the chat to request the roll is not working anymore.

3.
If you have an spell with an Attack roll and leave the boon/bane field empty it adds a boon to the roll.
You have to enter "+0" to make it stop that.

**Comment by Xacus** [comment]
Fixed in 1.1.5

Thanks :)

**Comment by TheAlaine** [comment]
> Fixed in 1.1.5
> 
> Thanks :)

Works perfectly now!

Just a quick question before this is closed. Is there a way to keep Dice So Nice from showing the creature rolls on the players side?

**Comment by Xacus** [comment]
There is a "whisper list" you can add to a roll. I'll try it and see if it does the job.

**Comment by Xacus** [comment]
I tried the whisper liste. The roll is only shown to the gm, but apparently no chat message is shown with the result. Must be a bug in the Dice So Nice module.

**Comment by TheAlaine** [comment]
> I tried the whisper liste. The roll is only shown to the gm, but apparently no chat message is shown with the result. Must be a bug in the Dice So Nice module.

Thank you for looking into it.
