### ISSUE TITLE
hide damage options from players

### ISSUE THREAD

**Issue by aeciobf** [Xacus/demonlord#16]
The damage options should appear only for the GM, as he is the only one who can change the health of all actors.
This would make the chat cleaner and avoid unnecessary clicks (player applying damage to yourself).
![Screenshot_2](https://user-images.githubusercontent.com/2878022/91666069-6b267100-ead0-11ea-99c0-17e1dc40fc4f.png)

**Comment by Xacus** [comment]
You're absolutely right about that. I'll removed it in the next update.

**Comment by Xacus** [comment]
In the 1.2.1 release.
