### ISSUE TITLE
Talents not keeping values

### ISSUE THREAD

**Issue by TheAlaine** [Xacus/demonlord#17]
Hi i made an Folder for Talents where i put in stuff like Combat Prowess so i can drag it on an char.
In one of the past releases this was working with no problems but now if i enter a value like 1d6 on the dmg part of an attack or enbale healing options the setting is gone after i close the window.
That only happens on talents that are not on characters. If i edit one on char it keeps the value and works.

PS: Thanks for all the releases :)

**Comment by TheAlaine** [comment]
PS: This seems to only affect new talents that i create, old ones i can edit like normal.

**Comment by Xacus** [comment]
Fixed in version 1.2.5.

**Comment by TheAlaine** [comment]
Works again, thank you.
