### ISSUE TITLE
Private/Blind rolls for Creatures not functioning as expected

### ISSUE THREAD

**Issue by Cham-iel** [Xacus/demonlord#18]
I was doing some test rolls for a creature's attacks, attributes, etc and noticed that even when I had the Private/Blind GM roll option selected the proper obfuscation was not applied to the rolls from ANY creature. If this is an intentional design choice I'd like to request the ability to disable it as I like to do rolls without my players necessarily knowing when I have or what the result was.
![privateroll](https://user-images.githubusercontent.com/71223361/93022131-fe6da500-f5ac-11ea-9173-8ceb73e75cd7.png)

**Comment by Xacus** [comment]
I'll implement some changes in the next version:

1. I'll take into account when Private GM Roll is selected. You as a GM vil only get the message.
2. I'll add a system setting so you can hide the Creature Attack stat. Necessary so I don't break the current functionality.

You'll be able to make GM Private rolls and rolls where all can see the message but only you as a gm can see the result (creature attack result).

Please join the Discord Server if you have not already: https://discord.gg/vc86Py

**Comment by Xacus** [comment]
Published Update 1.2.6

Give it a run and see if it's solves your needs.

**Comment by Cham-iel** [comment]
Working perfectly. Thanks much for the quick response, and for all your work on bringing the system to Foundry.
