### ISSUE TITLE
Does the newest release work with 0.7.5 in foundry?

### ISSUE THREAD

**Issue by TheAlaine** [Xacus/demonlord#23]
Is the ONLY meant as only in 0.7.4+ or mean in 0.7.4 only

**Comment by Xacus** [comment]
At the point 0.7.4 was the only version it was running on, but it’s working on 0.7.5 too.

**Comment by TheAlaine** [comment]
Awesome, will update foundry and the module after my session tomorrow :)

**Comment by Xacus** [comment]
I’ll soon make a release with Paths.
