### ISSUE TITLE
Empty Paths

### ISSUE THREAD

**Issue by TheAlaine** [Xacus/demonlord#24]
When i create a Path it has two fields Path and Description and bot are empty and not editable.

**Comment by Xacus** [comment]
I'm going to make a guide on the Discord server. 

The quick one is change the default sheet to PathSetup.

**Comment by Xacus** [comment]
And set it back when done or the players will see the wrong view.

**Comment by TheAlaine** [comment]
Should i have a different sheet than ActorSheet and ActorSheet2 ?

**Comment by Xacus** [comment]
Not on the Actor but the Path item

**Comment by TheAlaine** [comment]
> Not on the Actor but the Path item

Jeah i make a new item and select path instead of item ( this is where you can choose spell and ancestry and so on) and this is how i get an empty Path item where i can not do anything.

**Comment by TheAlaine** [comment]
Looks good i can make paths now.
