### ISSUE TITLE
Finishing editing a field stops editing for character sheets

### ISSUE THREAD

**Issue by DFreds** [Xacus/demonlord#28]
When I try to edit an NPC or PC, I want to be able to tab through the fields to make it faster or click the next field. However, every time I finish entering a field and either click the next field or try to tab over, it closes the editing context and I have to press it again. It slows me down considerably.

**Comment by DFreds** [comment]
I have no idea if you fixed this or if it was something else happening, but it's not longer happening for me. *shrug*

**Comment by Xacus** [comment]
When you drag a creature unto a scene and don't link it to the actor. Typically you don't want that. If the original actor is not in edit mode the new Token Actor defaults back to that mode if anything is changed on the creature. So it jumps out of edit mode when you change a value.
The trick is to keep your creatures in the Actors Directory in edit mode.

**Comment by DFreds** [comment]
Ah okay, thank you. I had no idea what I did differently
