### ISSUE TITLE
Include Feature field on Ancestry template [V 1.4.11]

### ISSUE THREAD

**Issue by aeciobf** [Xacus/demonlord#29]
Ancestries use Features.
Currently, only the field Talents exists on Ancestry template.

**Comment by Xacus** [comment]
Regarding Ancestries and Features: 
True and not true. Features is something I invented and use in my own game to write down things like Clockwork Form, Dwarf Hatred etc.

Apart from Attributes, Characteristics most ancestries have Talents like Iron Vulnerability, Shadowsight and Steal Identity.

<img width="524" alt="Screenshot 2020-11-27 at 21 30 41" src="https://user-images.githubusercontent.com/7236844/100482474-d1cf2100-30f7-11eb-80b0-de3e49ac34f7.png">

**Comment by aeciobf** [comment]
I see.

How to change the ancestry sheet from edit view to player view?
I don't get it.

Sorry by the inconvenience, guys!
![sotdl](https://user-images.githubusercontent.com/2878022/100794164-f844d300-33fb-11eb-8f8f-9ee32a16e15e.png)

**Comment by Xacus** [comment]
Ancestry is something completely different. You as a gm is always seeing this view. A Player sees automatically the player version if it. No need to change sheet.
