### ISSUE TITLE
Error on Level Up [V 1.4.11]

### ISSUE THREAD

**Issue by aeciobf** [Xacus/demonlord#30]
When leveling up, only the HP bonus is added.
Talents, Attributes bonus, languages, professions, etc, aren't added to character sheet.
![SotDL error](https://user-images.githubusercontent.com/2878022/100476706-0ecdf000-30c5-11eb-9242-c3e58ad919ec.jpg)

**Comment by Xacus** [comment]
![playersheet](https://user-images.githubusercontent.com/7236844/100480814-9ed65e80-30f2-11eb-8fc7-433b9814e6d7.png)

You properly forgot to change to the PlayerSheet. So right now you're seeing the GM setup view.

- The HP bonus is added automatically.
- Attribute bonuses are added when chosen by the player.

It dosen't add Talents, languages, professions to your character sheets. I could add Talents automatically but that's not necessarily a great idea. I have no intension of adding languages as an itemtype at least yet. Language and Professions have only little value to the game. I'll rather use 3-5 dags making something that has more value.
