### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Xacus** [Xacus/demonlord#41]
Should languages be items in the game?

spoken/read/write

**Comment by patrickporto** [comment]
@Xacus I believe that language should have two attributes only: spoken and read (read and write)

**Comment by Xacus** [comment]
Dwarf are the only Ancestry that starts with writing their language, academic professions and some religious professions gain write on a language known. 
I believe it is as it should be.

**Comment by patrickporto** [comment]
Right. However, some people with reading their language could write. I didn't find any examples in the core book when reading and writing are different learning.
