### ISSUE TITLE
Max insanity no longer tied to Will Score

### ISSUE THREAD

**Issue by TheAlaine** [Xacus/demonlord#44]
The max insanity vaule is 10 for some chars and 12 for another.
And it  seems locked to that vaule because changing the will via the ancestry does not effect the max insanity at all.
It worked before the updates.

**Comment by Xacus** [comment]
It's fixed in the next version 1.6.7.

But it's actually starting Insanity and not max Insanity. Insanity is equal your Will.

**Comment by Xacus** [comment]
Sorry, I did fix both bugs.

1. Insanity not updated when Will on Ancestry is changed.
2. Starting Insanity wasn’t transferred to character sheet.

**Comment by TheAlaine** [comment]
Thank you for fixing them ;)
