### ISSUE TITLE
Brazilian translation erros

### ISSUE THREAD

**Issue by aeciobf** [Xacus/demonlord#5]
- The attribute DEFENSE has been translated as DEFENSA. DEFESA is correct
- When creating a custom ancestry, the PERCEPTION characteristic was translated as PERFEIÇÃO

**Comment by Xacus** [comment]
I've change the first one.
Should Modificador de Perfeição be changed to Modificador de Percepção?

Thanks for helping out. :)

**Comment by aeciobf** [comment]
Hello!
Correct!
 Modificador de Perfeição to Modificador de Percepção.
