### ISSUE TITLE
Token Action HUD Challenge Rolls

### ISSUE THREAD

**Issue by AetherianRPG** [Xacus/demonlord#52]
Challenge rolls are not working if you try to roll them from Token Action HUD.

![Capturar](https://user-images.githubusercontent.com/68928934/112655140-dcdc5880-8e2e-11eb-829c-7954e34b75b8.PNG)

Edit: found out that this happens when you change system language to Portuguese.

**Comment by Xacus** [comment]
Thanks. I'll fix that.

**Comment by patrickporto** [comment]
Fixed https://github.com/espositos/fvtt-tokenactionhud/pull/213
