### ISSUE TITLE
Spells as items into Char Sheet

### ISSUE THREAD

**Issue by TheAlaine** [Xacus/demonlord#6]
Hi,

i can create an Spell as an item but if i want to drag it on a Character Sheet it gets added as a Tradition.
Is this an bug or intended?

Greetings,

TheAlaine

PS: Thank you so much for making this, you are awesome :)

**Comment by Xacus** [comment]
Yes, Spells was made in the beginning when I was less wiser then now and was implemented very clumsy.

Traditions is a Spell right now but just presentet differently. Spells below a Tradition is bound to the Tradition by it's parent id. You can't add spells the way it's made right now.

The plan is to redo magic. One of the next things on the list.

**Comment by TheAlaine** [comment]
> Yes, Spells was made in the beginning when I was less wiser then now and was implemented very clumsy.
> 
> Traditions is a Spell right now but just presentet differently. Spells below a Tradition is bound to the Tradition by it's parent id. You can't add spells the way it's made right now.
> 
> The plan is to redo magic. One of the next things on the list.

Thanks for the quick reply!
I will wait for the redo of magic then before i implement all the spells as items :)

**Comment by Xacus** [comment]
I have an idea how to make it and will start experimenting tomorrow.

**Comment by TheAlaine** [comment]
> I have an idea how to make it and will start experimenting tomorrow.

Nice, thank you so much.

**Comment by Xacus** [comment]
Fixed in 1.1.0
