### ISSUE TITLE
Ancestrys as Items

### ISSUE THREAD

**Issue by TheAlaine** [Xacus/demonlord#7]
Hi,

If you create an Ancestry as an item and drag it on the Char Sheet it adds an second Ancestry that you can not delete and it covers other stuff.

Greetings,
TheAlaine

**Comment by Xacus** [comment]
I deliberately made it as an item to later support drag/drop from an Items Directory.

I'll look at the possibility to delete the existing one when dropping a new one on the charactersheet.

**Comment by TheAlaine** [comment]
> I deliberately made it as an item to later support drag/drop from an Items Directory.
> 
> I'll look at the possibility to delete the existing one when dropping a new one on the charactersheet.

Thank you! 👍

**Comment by Xacus** [comment]
Fixed in 1.0.7

**Comment by TheAlaine** [comment]
Thank you :)
