### ISSUE TITLE
Monster Challenge Rolls with +0 mod

### ISSUE THREAD

**Issue by TheAlaine** [Xacus/demonlord#9]
Hello,

if you let an Monster make an challenge roll via the request in the chat window and the modifier of the attribute is +0 than the roll will be really high ( over 100 ). If the modifier is +1 or -1 then the monster rolls a D20 like normal. I tested this with agi and str and it looks like it makes d20+0 into a d200.

Regards,

TheAlaine

**Comment by TheAlaine** [comment]
Same result if i roll directly from the monster sheet.

**Comment by Xacus** [comment]
Thanks. Fixed in 1.1.1

**Comment by TheAlaine** [comment]
Thanks!
